---
title: "Utilitaires pour EcoFoG"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Contenu du package

Ce package contient des outils utiles aux membres de l'UMR.
Il est hébergé sur _GitHub_ sans vocation à être déposé sur CRAN.

Il contient :

- Des modèles de documents _RMarkdown_:

    - Un modèle d'article (produit au format PDF) bien formaté;
    - Un modèle de mémo (produit au format PDF) plus simple que l'article;
    - Un modèle de présentation Beamer;
    - Un modèle d'ouvrage (Bookdown): livre, rapport, thèse.
- Du code :
    - Des fonctions pour accéder aux données de la base Guyafor à partir du réseau local du campus de Kourou ou en VPN.


# Modèles de documents

Dans RStudio, créer un nouveau document de type Document R Markdown. 
L'assistant permet de choisir entre divers formats.

Cliquer sur _From template_: à partir de modèles installés par des packages. 
Les modèles du package EcoFoG sont affichés.

Ecrire le document dans RStudio : le mode d'emploi des modèles est dans leur contenu. 

Cliquer sur le bouton **Knit** de RStudio génère le document au format demandé.

Il est préférable de créer un projet RStudio pour bénéficier de toutes les possibilités : _File_ / _New Project_ puis utiliser l'assistant pour créer un projet à partir d'un dossier existant.

Voir la [documentation détaillée](https://ericmarcon.github.io/travailleR/chap-rediger.html).


# AutoMap

Application Shiny pour la création de cartes de Paracou.

Exécuter `Automap()` et compléter le formulaire pour obtenir une carte.

L'application ne fonctionne que si elle peut accéder à la base de données Guyafor, ou à une copie locale.


# Accès aux données

Les fonctions `Guyafor2df()` et `Paracou2df()` produisent des dataframes à partir de la base de données Guyafor.

# Documentation complète

https://EcoFoG.github.io/EcoFoG/ 
